# Generated by Django 4.2.4 on 2023-10-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-3-4'),
            preserve_default=False,
        ),
    ]
